### ISSUE TITLE
Android Epic

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2476]
This issue is for tracking other tasks that will need to be completed before the Android support is considered completed.

- #1195 
- #2445
- #444
- [x] Auto detect language on first launch
- [x] Bundle devilutionx.mpq in the apk and copy it to the external folder on startup
- [x] Build and include translations
- [x] Unicode font rendering
- [ ] #2959
- #1872
- [x] Russian translation

**Comment by AJenbo** [comment]
Closing this as the majority of issues have been solved and the rest can be tracked indivudally
